import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialPublicSchema1787454566464 implements MigrationInterface {
    name = 'InitialPublicSchema1787454566464'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "vehicle" ("id" SERIAL NOT NULL, "serial_number" character varying(50), "vin_number" character varying(50), "engine_number" character varying(50), "color" character varying(30), "brand" character varying(50), "model" character varying(50), "current_plate" character varying(20), "previous_plate" character varying(20), "state" character varying(30), "notes" text, "branch_office" character varying(50), "model_year" integer, "owners" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "plate_number" character varying(20) NOT NULL, "imagebase64" text, CONSTRAINT "PK_187fa17ba39d367e5604b3d1ec9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprl_sunarp_titles" ("titulo_year" character varying(10) NOT NULL, "titulo_number" character varying(20) NOT NULL, "titulo_extracted" boolean NOT NULL DEFAULT false, "plate" character varying(20), "pdf_base64" text, "attempts" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_02ad02f4decc66a34bbf66d92d5" PRIMARY KEY ("titulo_year", "titulo_number"))`);
        await queryRunner.query(`CREATE TABLE "sprl_sunarp" ("id" SERIAL NOT NULL, "version" integer NOT NULL, "registration_date" TIMESTAMP, "presentation_date" TIMESTAMP, "category" character varying(100), "act_type" character varying(100), "natural_participants" text, "legal_participants" text, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" integer NOT NULL, "plate_number" character varying(20), "titulo_year" character varying(10), "titulo_number" character varying(20), CONSTRAINT "PK_b1f7162cd0ac57d8b9ac4e506dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "soat_apeseg" ("id" SERIAL NOT NULL, "version" integer NOT NULL, "plate" character varying(20) NOT NULL, "nombre_compania" character varying(200), "fecha_inicio" character varying(50), "fecha_fin" character varying(50), "numero_poliza" character varying(100), "nombre_uso_vehiculo" character varying(100), "nombre_clase_vehiculo" character varying(100), "estado" character varying(50), "codigo_unico_poliza" character varying(100), "codigo_sbs_aseguradora" character varying(50), "fecha_control_policial" character varying(50), "nombre_contratante" character varying(200), "nombre_ubigeo" character varying(200), "numero_serie_motor" character varying(100), "numero_serie_chasis" character varying(100), "numero_aseguradora" character varying(100), "tipo_certificado" character varying(50), "fecha_creacion" character varying(50), "numero_asientos" character varying(50), "modelo_vehiculo" character varying(100), "marca" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by" integer NOT NULL, CONSTRAINT "PK_9b006e43775375289dcdcc3ebd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sbs_insurance" ("id" SERIAL NOT NULL, "plate_number" character varying(20) NOT NULL, "soat_accidents" integer DEFAULT '0', "soat_table_details" text, "insurance_accidents" integer DEFAULT '0', "insurance_table_details" text, "cat_accidents" integer DEFAULT '0', "cat_table_details" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b6574396ffa6bf21d96c9faf2d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pending_car_plates" ("id" SERIAL NOT NULL, "plate" character varying(10) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "a_is_loaded" boolean DEFAULT false, "a_search_attempts" integer NOT NULL DEFAULT '0', "b_is_loaded" boolean DEFAULT false, "b_search_attempts" integer NOT NULL DEFAULT '0', "c_is_loaded" boolean DEFAULT false, "c_search_attempts" integer NOT NULL DEFAULT '0', "d_is_loaded" boolean DEFAULT false, "d_search_attempts" integer NOT NULL DEFAULT '0', "e_is_loaded" boolean DEFAULT false, "e_search_attempts" integer NOT NULL DEFAULT '0', "f_is_loaded" boolean DEFAULT false, "f_search_attempts" integer NOT NULL DEFAULT '0', "g_is_loaded" boolean DEFAULT false, "g_search_attempts" integer NOT NULL DEFAULT '0', "h_is_loaded" boolean DEFAULT false, "h_search_attempts" integer NOT NULL DEFAULT '0', "i_is_loaded" boolean DEFAULT false, "i_search_attempts" integer NOT NULL DEFAULT '0', "j_is_loaded" boolean DEFAULT false, "j_search_attempts" integer NOT NULL DEFAULT '0', "k_is_loaded" boolean DEFAULT false, "k_search_attempts" integer NOT NULL DEFAULT '0', "l_is_loaded" boolean DEFAULT false, "l_search_attempts" integer NOT NULL DEFAULT '0', "m_is_loaded" boolean DEFAULT false, "m_search_attempts" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_d5daa859038515000f0c4fe67b0" UNIQUE ("plate"), CONSTRAINT "PK_a89e02393e80d051c304efdded6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "license_plate_master" ("id" SERIAL NOT NULL, "public_code" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "plate_number" character varying(20) NOT NULL, CONSTRAINT "UQ_8e1b570cd8f143b14fea0972cde" UNIQUE ("public_code"), CONSTRAINT "UQ_5f3a7df03a918c73d97be80dce5" UNIQUE ("plate_number"), CONSTRAINT "PK_d5c737a9a728a2f7392be7d7a4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inspeccion_vehicular" ("id" SERIAL NOT NULL, "plate_number" character varying(20) NOT NULL, "data" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c395fb00827b01148829a70b1e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "auth"."users" ADD "username" character varying`);
        await queryRunner.query(`ALTER TABLE "auth"."users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "auth"."users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auth"."users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "auth"."users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Revert deshabilitado a propósito: en producción estas tablas (vehicle,
        // sprl_sunarp*, soat_apeseg, sbs_insurance, pending_car_plates,
        // license_plate_master, inspeccion_vehicular) ya existían con datos reales
        // antes de que esta migración se registrara (se marcó como aplicada sin
        // ejecutar su `up`, porque el estado ya coincidía). Un `down` real haría
        // DROP TABLE sobre esos datos. Si de verdad necesitas revertir el schema
        // en un entorno nuevo/vacío, hazlo a mano revisando cada sentencia.
        throw new Error(
            'InitialPublicSchema1787454566464.down() está deshabilitado: revertiría tablas con datos reales de producción.',
        );
    }

}
